import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsProvider from "@/src/lib/StyledComponentsProvider";
import GlobalStyles from "@/src/styles/GlobalStyles";

import Header from "@/src/components/common/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStyles />
        <StyledComponentsProvider>
          <Header />
          {children}
        </StyledComponentsProvider>
      </body>
    </html>
  );
}
